# Generated by Django 4.2.3 on 2023-07-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
